### PR TITLE
Update type definition

### PR DESCRIPTION
**Pull request by caseyhoward**
Allow #object to take a constructor with arguments.

### CODE REVIEW

**Comment by caseyhoward** [comment]
Fixes https://github.com/testdouble/testdouble.js/issues/184

**Comment by searls** [comment]
Since I don't use TS I am going to follow my TS policy of just merging whatever people send in

**Comment by caseyhoward** [comment]
That was fast. Thanks!

**Comment by jdantonio** [comment]
Landed in 0.11.1

**Comment by jdantonio** [comment]
errr, 1.11.1

**Pull request merged**
