### PR TITLE
Add typings for config function

### LINKED ISSUE #222: Add td.config() to index.d.ts
Right now, you have to cast `td as any` to call `.config()` on it. It would be nice to have that function be part of the type definition file.

### PR DESCRIPTION
**Pull request by lumaxis**
Fixes #222

### CODE REVIEW

**Comment by searls** [comment]
Merged without reading or understanding

**Comment by searls** [comment]
Landed in 2.1.1

**Comment by lumaxis** [comment]
Awesome! Thanks for the quick release 🙂 
And you really should give TypeScript a chance, it's pretty nice 😉

**Comment by searls** [comment]
It's on my list!

**Pull request merged**
