### PR TITLE
explain plan better in stubbing description

### LINKED ISSUE #126: td.explain should indicate thenCallback / thenResolve / thenReject from thenReturn
```javascript
var fn = td.func();
td.when(fn()).thenResolve(true);
console.log(td.explain(fn));
```

**Expected**
```javascript
{
  callCount: 0,
  calls: [],
  description: 'This test double has 1 stubbings and 0 invocations.\n\nStubbings:\n  - when called with `()`, then resolve `null`.',
  isTestDouble: true,
}
```

The important part is `then resolve 'null'`.

**Actual**
```javascript
{
  callCount: 0,
  calls: [],
  description: 'This test double has 1 stubbings and 0 invocations.\n\nStubbings:\n  - when called with `()`, then return `null`.',
  isTestDouble: true,
}
```

I can make a pull request if accepted.

### PR DESCRIPTION
**Pull request by Moeriki**
Fixes #126.

Feedback very welcome!

### CODE REVIEW

**Comment by searls** [comment]
Could you wrap the thenCallback args with ()? Otherwise looks good

**Comment by Moeriki** [comment]
I changed `then callback 'null', '8'` to `then callback (null, 8)` for `returnCallback` plan.

**Comment by searls** [comment]
For consistency sake could you also wrap the `()` in backticks like the other values? Once you have that I'm good to merge

**Comment by Moeriki** [comment]
Makes sense. Updated.

**Comment by searls** [comment]
Landed in 1.6.1

**Pull request merged**
