### PR TITLE
Generate test double name for a Proxy test double

### LINKED ISSUE #112: Wrong test double name for proxies
Cloned the project - current commit is `4c4c1b7`. Then `npm run test`. Got 2 failures:

```
  1) td.object creating a proxy object (ES2015; only supported in FF + Edge atm) then this.testDouble.toString() === '[test double object for "Thing"]':
     Error: return value is false
     Expected '[test double object]' to strictly equal '[test double object for "Thing"]'
     Comparison: this.testDouble.toString() === '[test double object for "Thing"]'

  2) td.object creating a proxy object (ES2015; only supported in FF + Edge atm) then this.testDouble.foo.toString() === '[test double for "Thing#foo"]':
     Error: return value is false
     Expected '[test double for "#foo"]' to strictly equal '[test double for "Thing#foo"]'
     Comparison: this.testDouble.foo.toString() === '[test double for "Thing#foo"]'
```

I'm dropping this error report while I'm trying to investigate why this is happening.

### PR DESCRIPTION
**Pull request by mgryszko**
Fixes #112. Tested with Node 6.2.1.

### CODE REVIEW

**Comment by mgryszko** [comment]
Pending issue: `npm run test:all` fails on `est:example:lineman` script.

When executing `lineman spec-ci`, it fails on `jshint:files` task. Before `jshint:files`, there are some warnings emitted:

```
Running "coffee:compile" (coffee) task
>> Destination (generated/js/app.coffee.js) not written because compiled files were empty.
>> Destination (generated/js/spec.coffee.js) not written because compiled files were empty.
>> Destination (generated/js/spec-helpers.coffee.js) not written because compiled files were empty.
```

**Comment by searls** [comment]
Thanks!

Please don't update dist in PRs, we only update it on release tag commits

**Comment by mgryszko** [comment]
Commits recreated without dist.

**Comment by searls** [comment]
Seems legit :+1:

**Pull request merged**
