### PR TITLE
Adding reset() to the Readme.md

### PR DESCRIPTION
**Pull request by BrianGenisio**

### CODE REVIEW

**Comment by searls** [comment]
:sparkles:

**Comment by kenhowardpdx** [comment]
@searls I don't see this documentation in master. Can you verify that test doubles can be reset as a one-off? I'm not seeing this behavior.

**Comment by searls** [comment]
Eek you're right. I must have misread the OP's patch. Resets are always global

**Comment by searls** [comment]
@kenhowardpdx this teaches me to read from my phone -- no resets are always global. There is not a one-off reset mechanism.

**Comment by kenhowardpdx** [comment]
@searls This is fine by me. I was looking for a good pattern and stumbled on this PR which made me wonder if there was a way to do this. Glad to know the current documentation is accurate!

Keep up the good work!

**Pull request merged**
