### PR TITLE
fix missing `listReplacedModules` in ESM barrel file

### PR DESCRIPTION
**Pull request by JakobJingleheimer**
When this was added in v3.20.0, it was included in the CJS barrel file, but not the ESM one.

### CODE REVIEW

**Comment by searls** [comment]
Apologies @JakobJingleheimer, I've never really understood the mjs stuff and now CI is failing for maybe-related, but probably bitrot reasons, also pertaining to ESM. @giltayar could you please take a quick look?

**Comment by JakobJingleheimer** [comment]
Oh! 🤦‍♂️ one sec

**Comment by searls** [comment]
Oh wow, CI caught something. Neat.

**Comment by JakobJingleheimer** [comment]
@searls any chance a patch could be released for this?

(And also possibly upgrade quibble to include this upstream fix https://github.com/testdouble/quibble/pull/108)

**Comment by searls** [comment]
Landed in v3.20.2

**Pull request merged**
