### PR TITLE
TypeScript typing thenResolve takes variable args

### PR DESCRIPTION
**Pull request by miyu**
For consistency with thenReturn - no changes to library necessary.

### CODE REVIEW

**Comment by searls** [comment]
Build failure was erroneous. Restarted.

@duluca will merge if you approve change

**Comment by duluca** [comment]
It'd be great if this PR is updated once #259 is merged, so there's a valid CI run against this change.

TODO:
[ ] Update from master once #259 is merged
[ ] Add a line to test.ts that exercises the spread feature 
[ ] Update this PR and make sure CI checks pass

**Comment by searls** [comment]
ok @duluca, #260 (nay #259) is now merged, so this should be doable now.

**Comment by miyu** [comment]
Merged #260, changed test.ts. I figure if the spread case is covered the one-arg case is covered?

**Comment by duluca** [comment]
@miyu I concur

**Comment by searls** [comment]
Stupid Q: does `thenResolve()` actually support multiple promises? I don't think we have a test for this in `test/src/when-test.coffee`. Can you validate for me?

**Comment by miyu** [comment]
I'm using it in my own tests.

**Comment by searls** [comment]
Sure enough. I added some tests for this to ensure I don't break you in #263

**Pull request merged**
