### PR TITLE
Upgrade to lodash 4.15.0

### PR DESCRIPTION
**Pull request by searls**
**Not ready to merge**

- [x] fix 71 failing unit tests
- [x] get `npm run test:ci` to pass

### CODE REVIEW

**Comment by searls** [comment]
Down to 39 failures…

**Comment by searls** [comment]
down to 19 failures…

**Comment by searls** [comment]
down to 0 unit test failures, moving on to `npm run test:ci`

**Comment by searls** [comment]
ok,`npm run test:ci` is also passing, but the distribution went from 460KB to 576KB 😦 

hey @jasonkarns I'd love your opinion before clicking merge:

1. anything else i should check before merging this to be sure the 3->4 migration was safe

2. how much effort might it be to only require the lodash funcs we actually use?

**Comment by searls** [comment]
Welp, I did the individual requires and was pretty shocked by the size difference

```
$ du -h dist/*
564K	dist/testdouble-big-lodash-4.js
200K	dist/testdouble-lodash-individual.js
452K	dist/testdouble.js
```

This PR bumped us from 452K to 564K, but by individually `require`'ing our lodash functions, it gets us back down to 200K, which seems like a definite good. AFAICT I'm not using any lodash functions dynamically.

**Comment by searls** [comment]
This failure is due to some 0.12 network issue. Merging with reckless abandon

**Comment by searls** [comment]
Landed in 1.7.0

**Comment by jdalton** [comment]
Cool. For non-coffee projects you can use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to make cherry-picking easier. Then if using webpack [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) would cut the bundle size further.

**Pull request merged**
