### PR TITLE
full example tdd using tdjs

### PR DESCRIPTION
**Pull request by okandas**
Test-Driving JavaScript Applications - The Pragmatic Bookshelf

this book uses sinon and I feel sinon is not as straight forward as tdjs ... So I redid the example using 
tdjs ...

### CODE REVIEW

**Comment by searls** [comment]
A  couple questions:
* Is this folder a carbon copy of the book's codebase, but with sinon snippets replaced with td.js ones? Did you editorialize at all? 
* What license did pragprog release these exercises over? If it's not licensed in some open way or otherwise give permission, we can't host it in this repo without likely infringing on their copyright

**Comment by okandas** [comment]
Re wrote all as i was learning from the book .. Didn't use sinon .. Its not
a carbon copy .. You could see the repo on my github ... okandas/tdd with
all the commits ...

My first pull request and may have looked over looked the licensing

**Comment by searls** [comment]
Hey @okandas, I've decided against merging this into the repo, but I really value your effort. Would you mind extracting this out to your own repo? If so, I'd be more than happy to find a place to link to it from our docs or readme.

Cheers!

**Comment by okandas** [comment]
@searls no problem .. this is a link to the full repo.. https://github.com/okandas/tdd

**Pull request closed without merging**
