### PR TITLE
Merge Circle CI config to master

### PR DESCRIPTION
**Pull request by searls**
- [x] rebase if needed
- [x] see travis still passing
- [x] see circle passing

### CODE REVIEW

**Comment by zzak** [comment]
Thanks for moving on this!

I have no idea why the cover command fails on node 4 and 6.

I'd also like to re-enable npm caching once it's fixed, which should save a little more time.

Please let me know if you have any questions about our stuff!

**Comment by searls** [comment]
Hey @zzak what did you mean by fixing caching once fixed? Now that the build is green can you re-enable caching or did you mean to say the feature itself was broken?

**Comment by searls** [comment]
@zzak since it's probably your 2am right now, I'm just going to merge what we have since it's definitely faster than Travis has been and I'd like to try it out for a couple weeks. Please feel free to try a subsequent PR for module caching

**Comment by zzak** [comment]
@searls I turned it off here to make sure that wasn't the reason it failed:
https://github.com/testdouble/testdouble.js/pull/349/commits/1a7f0d696093195f16df03161f8dd6f936e7a5a8

**Comment by searls** [comment]
Revert attempted here https://github.com/testdouble/testdouble.js/blob/master/.circleci/config.yml does that look right?

**Comment by zzak** [comment]
@searls Looks like that wasn't a clean commit because it changed  `npm` commands, I will send a new patch.

**Pull request merged**
